language: node_js

node_js:
  - "10"

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --ignore-engines

script:
  - yarn run lint
  - yarn test

after_success: npx codecov
